### ISSUE TITLE
成功搭建之后出现接收回复错误 已填写KEY

### ISSUE THREAD

**Issue by jia110** [geekr-dev/geekchat#6]
<img width="570" alt="微信截图_20230319170817" src="https://user-images.githubusercontent.com/38829156/226165104-e23ccc4d-df42-4481-9543-e2f76dbfe5c5.png">

**Comment by lpzhi** [comment]
响应 403

**Comment by geekr-dev** [comment]
看下是不是cors问题 另外不支持swoole/roadrunner之类常驻内存http服务器
